// Copyright Christian Corsica. All Rights Reserved.


export const blogs = [
    {
        thumbnail: "https://i.imgur.com/Mfeq94Y.jpeg",
        title: "In the Beginning",
        date: "Sep 24, 2020",
        filename: "in-the-beginning",
        tags: ["beginnings", "introduction", "new", "filler"],
    },
    {
        thumbnail: "https://i.imgur.com/FKK2Ey0.png",
        title: "Week 1: Concepts and Version Control",
        date: "Oct 5, 2020",
        filename: "week-1-concepts-and-version-control",
        tags: ["Git", "Github", "Tom Looman", "cow", "pig", "chicken", "blob","samurai", "cube", "dice"],
    },
    {
        thumbnail: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExcm93c3plNnFpdDQ3dTJsZDN5aGsyMDI4MGJrbGVoZWZ6dm4yOG90YSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/icYRecpPm0iLhQX7Vg/giphy.gif",
        title: "Week 2: Moving Around",
        date: "Oct 19, 2020",
        filename: "week-2-moving-around",
        tags: ["first steps", "falling objects"],
    },
    {
        thumbnail: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHdzZ3Z6ejU4bDVobWUwcTdmNTU0eTI4a2lvd2lmNmpxZG1sMTB1aiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xMcA6GZptd9aT5LOxx/giphy.gif",
        title: "Week 3: Streamlining Gifs",
        date: "Oct 27, 2020",
        filename: "week-3-streamlining-gifs",
        tags: ["dev", "blog", "giffer", "adobe", "premiere", "after effects", "video", "program", "github", "quality"],
    },
    {
        thumbnail: "https://i.imgur.com/Frnb8uY.png",
        title: "Week 4: Halloween",
        date: "Nov 3, 2020",
        filename: "week-4-halloween",
        tags: ["pumpkins", "houdini", "hda", "download", "trick or treat", "renders", "mantra", "ray tracing"],
    },
    {
        thumbnail: "https://i.imgur.com/v7hH9WI.png",
        title: "Week 5: More Concepts",
        date: "Nov 18, 2020",
        filename: "week-5-more-concepts",
        tags: ["concepts", "drawings", "narwhal", "turtle", "sloth", "moving"],
    },
    {
        thumbnail: "https://media.giphy.com/media/zLooKuKAXXuIkFmtRW/giphy.gif",
        title: "Week 6: Moving Up",
        date: "Nov 23, 2020",
        filename: "week-6-moving-up",
        tags: ["movement system", "physics", "lerp", "slow motion"],
    },
    {
        thumbnail: "https://i.imgur.com/HpG77DR.png",
        title: "Week 7: Discovering Weaknesses/Deploying",
        date: "Nov 30, 2020",
        filename: "week-7-discovering-weaknesses-deploying",
        tags: ["physics", "formula", "math", "velocity", "gravity", "c++", "cpp", "prediction", "build", "macos", "UE", "unreal engine"],
    },
    {
        thumbnail: "https://i.imgur.com/g22cU2l.jpeg",
        title: "Week 8: Turning Physics On/Off",
        date: "Dec 8, 2020",
        filename: "week-8-turning-physics-on-off",
        tags: ["physics", "UE", "unreal engine", "super smash brothers", "platform", "overlap", "components", "trello", "gifs"],
    },
    {
        thumbnail: "https://i.imgur.com/gAfZq9u.png",
        title: "Week 9: Profiling and Optimizing",
        date: "Dec 14, 2020",
        filename: "week-9-profiling-and-optimizing",
        tags: ["UE", "unreal engine", "insights", "video games", "stat", "unit", "gpu", "vsync", "bound", "download", "size", "packaging"],
    },
    {
        thumbnail: "https://i.imgur.com/E7UhrNu.png",
        title: "Week 10: Sculpting, Topology, and UVs",
        date: "Dec 21, 2020",
        filename: "week-10-sculpting-topology-and-uvs",
        tags: ["blobber", "character", "sculpt", "sketch", "paper", "photoshop", "Adobe Medium", "VR", "Zbrush", "Topogun", "Houdini", "Maya", "Side FX Labs", "Low poly High"],
    },
    {
        thumbnail: "https://i.imgur.com/fMnvIvX.jpeg",
        title: "Week 11: Baking, Texturing, and The Start of Something New",
        date: "Dec 28, 2020",
        filename: "week-11-baking-texturing-and-the-start-of-something-new",
        tags: ["blobber", "character", "sculpt", "3D print", "Maya", "Houdini", "Rigging", "Animate", "Digital Content Creation", "DCC", "Pros", "Cons", "Marmoset Toolbag", "Substance Painter", "Ambient Occlusion", "Normal", "Github", "Piper"],
    },
    {
        thumbnail: "https://i.imgur.com/py5dppx.png",
        title: "Week 12: Building Maya Plugin with CLion, New Character, and Adding QMenu to Maya Main Menu",
        date: "Jan 4, 2021",
        filename: "week-12-building-maya-plugin-with-clion-new-character-and-adding-qmenu-to-maya-main-menu",
        tags: ["waooer", "character", "jetbrains", "clion", "rider", "cmake", "Maya plugin", "Visual Studio", "toolchain", "marmoset", "Adobe Medium", "VR", "piper", "script", "python", "menu", "github"],
    },
    {
        thumbnail: "https://i.imgur.com/MXeGwqr.png",
        title: "Week 13: A cow and a Matrix",
        date: "Jan 11, 2021",
        filename: "week-13-a-cow-and-a-matrix",
        tags: ["mooer", "character", "marmoset", "piper", "rigging", "constraint", "code", "script", "maya", "math"],
    },
    {
        thumbnail: "https://i.imgur.com/RI6rTWR.png",
        title: "Week 14: Oliver and more Matrices",
        date: "Jan 18, 2021",
        filename: "week-14-oliver-and-more-matrices",
        tags: ["oliver", "character", "marmoset", "piper", "rigging", "constraint", "code", "script", "maya", "math", "VR", "Adobe Medium", "process", "digital content creation", "parent matrix constraint", "python", "pymel"],
    },
    {
        thumbnail: "https://i.imgur.com/QVKmTWf.gif",
        title: "Week 15: Piper Checkpoint",
        date: "Jan 25, 2021",
        filename: "week-15-piper-checkpoint",
        tags: ["FK", "IK", "chains", "rigging", "maya", "soft IK", "pole vector", "source code", "open", "github", "blobber", "character"],
    },
    {
        thumbnail: "https://i.imgur.com/5wtENKF.png",
        title: "Week 16: Johnny Jupiter and Space Switching",
        date: "Feb 2, 2021",
        filename: "week-16-johnny-jupiter-and-space-switching",
        tags: ["friends", "sculpt", "character", "Johnny Jupiter", "3D", "marmoset", "matrix", "piper", "python", "pymel"],
    },
    {
        thumbnail: "https://i.imgur.com/dNiSh7p.png",
        title: "Week 17: Concepts, 3D printing, and Graphics",
        date: "Feb 15, 2021",
        filename: "week-17-concepts-3d-printing-and-graphics",
        tags: ["starbuster", "muffiner", "sunflower", "cacter", "johnny jupiter", "line up", "waooer", "characters", "ShaderFX", "maya", "blinn", "Norrksen PBR", "ambient occlusion", "roughness", "metallic"],
    },
    {
        thumbnail: "https://i.imgur.com/OPGipmh.png",
        title: "Week 17.5: How to Set a ShaderFX Setting",
        date: "Feb 15, 2021",
        filename: "week-17-5-how-to-set-a-shaderfx-setting",
        tags: ["maya", "pymel", "python", "example", "norrsken PBR", "unique ID", "documentation", "code"],
    },
    {
        thumbnail: "https://i.imgur.com/vlZt9wY.jpeg",
        title: "Week 18: A Clucker and How To Mirror Joints Without Joint Orient",
        date: "Feb 22, 2021",
        filename: "week-18-a-clucker-and-how-to-mirror-joints-without-joint-orient",
        tags: ["maya", "pymel", "python", "code", "clucker", "chicken", "character", "VR", "Adobe Medium", "process", "rotation"],
    },
    {
        thumbnail: "https://i.imgur.com/zvCgmXa.png",
        title: "Week 19: Chicken Sounds",
        date: "Mar 1, 2021",
        filename: "week-19-chicken-sounds",
        tags: ["chicken", "clucker", "marmoset", "viewer", "short", "render", "cute", "sad", "crazy"],
    },
    {
        thumbnail: "https://i.imgur.com/KytZGzt.png",
        title: "Week 20: How to Create a Curve from a Cross Section of a Mesh in Maya and Houdini",
        date: "Mar 8, 2021",
        filename: "week-20-how-to-create-a-curve-from-a-cross-section-of-a-mesh-in-maya-and-houdini",
        tags: ["chicken", "clucker", "plane", "code", "python", "gist", "github", "normal", "edges", "SideFX Labs", "SOPs", "nodes", "HDA"],
    },
    {
        thumbnail: "https://i.imgur.com/DNoB5CS.gif",
        title: "Week 21: Banking via Sliding Foot Pivot Roll",
        date: "Mar 15, 2021",
        filename: "week-21-banking-via-sliding-foot-pivot-roll",
        tags: ["mooer", "dynamic pivot", "curves", "maya", "rigging", "script", "python", "github", "gif", "cow"],
    },
    {
        thumbnail: "https://i.imgur.com/fsmgWHV.gif",
        title: "Week 22: Python 3/Maya 2022, Local FK Controls and Switcher GUI",
        date: "Mar 29, 2021",
        filename: "week-22-python-3-maya-2022-local-fk-controls-and-switcher-gui",
        tags: ["leg", "Johnny Jupiter", "updating", "converter", "spaces", "local", "world", "body", "foot", "thigh", "individual channels", "rigging"],
    },
    {
        thumbnail: "https://i.imgur.com/GmIZvra.gif",
        title: "Week 23: Reverse IK",
        date: "Apr 5, 2021",
        filename: "week-23-reverse-ik",
        tags: ["leg", "Johnny Jupiter", "hacky", "piper", "rigging", "refactor", "message attributes", "😊", "💀"],
    },
    {
        thumbnail: "https://i.imgur.com/GsxGYtX.gif",
        title: "Week 24: Volumetric FK Scaling and Reference Retargeting",
        date: "Apr 12, 2021",
        filename: "week-24-volumetric-fk-scaling-and-reference-retargeting",
        tags: ["leg", "blobber", "mooer", "cow", "squash and stretch", "shearing", "matrix", "math", "node editor", "unreal engine", "c++", "rigging", "decompose", "animation"],
    },
    {
        thumbnail: "https://i.imgur.com/WVbLLTz.gif",
        title: "Week 25: Volumetric IK",
        date: "Apr 19, 2021",
        filename: "week-25-volumetric-ik",
        tags: ["legs", "blobber", "mooer", "cow", "squash and stretch", "animation", "scale", "unreal engine", "maya", "export", "FBX", "retargeting"],
    },
    {
        thumbnail: "https://i.imgur.com/eZTIHhN.gif",
        title: "Week 26: How to Register \"Repeat Last Command\" and Orient To Face, Edge, or Vertex Normal in Maya",
        date: "Apr 26, 2021",
        filename: "week-26-how-to-register-repeat-last-command-and-orient-to-face-edge-or-vertex-normal-in-maya",
        tags: ["action", "python", "code", "pymel", "scripting", "gist", "metaprogramming", "transform", "matrix", "world space", "cross product", "direction", "vector math", "clipper"],
    },
    {
        thumbnail: "https://i.imgur.com/kyCYCUn.gif",
        title: "Week 27: Global Scaling and Rig Organization",
        date: "May 3, 2021",
        filename: "week-27-global-scaling-and-rig-organization",
        tags: ["blobber", "Unreal Engine", "constraint", "maya", "hierarchy", "rig", "outliner", "clean"],
    },
    {
        thumbnail: "https://i.imgur.com/0pyfYth.png",
        title: "Week 28: Icons/Buttons, Colors, and Bug Fixes",
        date: "May 10, 2021",
        filename: "week-28-icons-buttons-colors-and-bug-fixes",
        tags: ["space switcher", "GUI", "art", "controls", "Maya", "study", "blindness", "maritime", "coding", "accessibility"],
    },
    {
        thumbnail: "https://i.imgur.com/KHXFgGz.jpeg",
        title: "Week 29: High-Poly Wraps",
        date: "May 26, 2021",
        filename: "week-29-high-poly-wraps",
        tags: ["food", "delicious", "yummy", "succulent", "maya", "proximity", "script", "new", "Blobber", "dance", "happy", "piper", "menu"],
    },
    {
        thumbnail: "https://i.imgur.com/4bA17Zs.gif",
        title: "Week 30: Orient Space",
        date: "May 31, 2021",
        filename: "week-30-orient-space",
        tags: ["Johnny Jupiter", "maya", "script", "attribute", "controls", "forward kinematics", "piper", "to do list"],
    },
    {
        thumbnail: "https://i.imgur.com/12AaXTr.gif",
        title: "Week 31: Piper's To-Do Complete!",
        date: "Jun 8, 2021",
        filename: "week-31-piper-s-to-do-complete",
        tags: ["Johnny Jupiter", "maya", "script", "attribute", "controls", "twist", "forearm", "rigging", "joints", "math", "swing", "Knockout City"],
    },
    {
        thumbnail: "https://i.imgur.com/zJ3a7QN.gif",
        title: "Week 32: First Animation",
        date: "Jun 21, 2021",
        filename: "week-32-first-animation",
        tags: ["Blobber", "jumping", "Maya", "scaling", "uniform", "Unreal Engine", "modify bone", "reading curve"],
    },
    {
        thumbnail: "https://i.imgur.com/XR2xReL.gif",
        title: "Week 33: Squash and Stretch and Looking Sideways",
        date: "Jun 28, 2021",
        filename: "week-33-squash-and-stretch-and-looking-sideways",
        tags: ["Blobber", "jumping", "Unreal Engine", "skeleton", "baked", "runtime", "modify bone"],
    },
    {
        thumbnail: "https://i.imgur.com/p7YQmID.gif",
        title: "Week 34: Jump Animation and Rig Improvements",
        date: "Jul 5, 2021",
        filename: "week-34-jump-animation-and-rig-improvements",
        tags: ["Blobber", "jumping", "Unreal Engine", "script", "context manager", "python", "squash and stretch", "montage", "animation", "pose", "idle", "gif"],
    },
    {
        thumbnail: "https://i.imgur.com/lC3DSZc.gif",
        title: "Week 35: A Cow Munches on Grass and a Blob Squashes and Stretches",
        date: "Jul 12, 2021",
        filename: "week-35-a-cow-munches-on-grass-and-a-blob-squashes-and-stretches",
        tags: ["mooer", "animation", "idle", "unreal engine", "bouncing", "blobber", "list", "to do"],
    },
    {
        thumbnail: "https://i.imgur.com/ZxkF2K3.png",
        title: "Week 36: A Bendy Stick Figure in 3D",
        date: "Sep 7, 2021",
        filename: "week-36-a-bendy-stick-figure-in-3d",
        tags: ["pivot animator", "soccer", "short", "model", "rig", "maya", "rigging", "model"],
    },
    {
        thumbnail: "https://i.imgur.com/5GizjJ4.png",
        title: "Week 37: Back At It Again",
        date: "Feb 21, 2022",
        filename: "week-37-back-at-it-again",
        tags: ["animation", "soccer", "project 214", "unreal engine", "render", "short", "back 4 blood", "relative path", "futsal"],
    },
    {
        thumbnail: "https://i.imgur.com/Pl7M448.gif",
        title: "Week 38: Select Fractionally Weighted Verts in Maya Script, A Jumping Cow, and A Spreadsheet",
        date: "Mar 7, 2022",
        filename: "week-38-select-fractionally-weighted-verts-in-maya-script-a-jumping-cow-and-a-spreadsheet",
        tags: ["piper", "script", "rigging", "skinning", "vertices", "chains", "hierarchy", "gist", "game", "mooer", "jumping", "google sheets", "production", "tracker", "animation list"],
    },
    {
        thumbnail: "https://i.imgur.com/QSBTSps.png",
        title: "Week 39: Character Selection and Async Loading",
        date: "Mar 14, 2022",
        filename: "week-39-character-selection-and-async-loading",
        tags: ["blueprints", "unreal engine", "asynchronously", "execution", "for loop", "code", "nodes"],
    },
    {
        thumbnail: "https://i.imgur.com/vLf04vh.gif",
        title: "Week 40: Piper Updates and an Idle",
        date: "Mar 21, 2022",
        filename: "week-40-piper-updates-and-an-idle",
        tags: ["animation", "Johnny Jupiter", "qt.py", "git", "submodules", "maya", "idle", "example", "code", "python", "script"],
    },
    {
        thumbnail: "https://i.imgur.com/9eVxKLx.png",
        title: "Week 41: Mirroring Rig with A Python Script in Maya",
        date: "Mar 28, 2022",
        filename: "week-41-mirroring-rig-with-a-python-script-in-maya",
        tags: ["left", "right", "side", "suffixes", "gist", "code", "example", "waooer", "narwhal", "happy", "animation", "wagging", "tail"],
    },
    {
        thumbnail: "https://i.imgur.com/9qCBDI5.png",
        title: "Week 42: How to Build Unreal Project on M1 Mac with XCode 13.3",
        date: "Apr 4, 2022",
        filename: "week-42-how-to-build-unreal-project-on-m1-mac-with-xcode-13-3",
        tags: ["packaging", "building", "macos", "launcher", "code", "binaries", "mono", "source", "tutorial", "video", "Johnny Jupiter", "Hello World"],
    },
    {
        thumbnail: "https://i.imgur.com/3v9Qwy2.png",
        title: "Week 43: Evaluating UE5 for iOS and How to Fade Material WITHOUT Blueprint Timelines",
        date: "Apr 11, 2022",
        filename: "week-43-evaluating-ue5-for-ios-and-how-to-fade-material-without-blueprint-timelines",
        tags: ["pros", "cons", "Epic", "Unreal Engine", "iOS", "MacOS", "M1", "benefits", "downsides", "blueprint", "graph editor", "dynamic instance", "code", "cpp", "c++"],
    },
    {
        thumbnail: "https://i.imgur.com/PrQgtUL.jpeg",
        title: "Week 44: Continuous Integration for Unreal Engine iOS Projects with Jenkins",
        date: "Apr 25, 2022",
        filename: "week-44-continuous-integration-for-unreal-engine-ios-projects-with-jenkins",
        tags: ["short", "github", "MacOS", "beginner", "tutorial", "build", "shell", "scripts"],
    },
    {
        thumbnail: "https://i.imgur.com/sZ1Pu4R.png",
        title: "Week 45?: Piper Lives Up to Its Name",
        date: "Sep 25, 2022",
        filename: "week-45-piper-lives-up-to-its-name",
        tags: ["update", "dev log", "Unreal Engine", "script", "python", "pipeline", "export", "metadata", "Maya", "burnout", "material", "blend", "landscape", "texture", "technical art"],
    },
    {
        thumbnail: "https://i.imgur.com/xnt61E5.png",
        title: "New Site: Who Dis",
        date: "Aug 3, 2025",
        filename: "new-site-who-dis",
        tags: ["wix", "github", "pages", "website", "html", "javascript", "css", "webstorm", "jetbrains", "phpstorm", "hyperskill", "converter", "mathml", "markdown"],
    }
]